import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { HTML5Backend } from "react-dnd-html5-backend";
// import { DndProvider } from "react-dnd";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KargaKarga Case",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <DndProvider backend={HTML5Backend}> */}
      <body className={inter.className}>{children}</body>
      {/* </DndProvider> */}
    </html>
  );
}
